name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: code-compass-api
  PYTHON_VERSION: '3.11'

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Python Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Export dependencies for Azure
        working-directory: backend
        run: |
          # Compile all project dependencies into requirements.txt
          uv pip compile pyproject.toml --output-file=requirements.txt
          cat requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-backend
          path: backend

  deploy:
    name: Deploy Python Backend to Azure App Service
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-backend
          path: .

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: python-backend
